//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace wgvmi15_net_core {
    
    
    public partial class UserInfo {
        
        /// <summary>
        /// Controle GetToken.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GetToken;
        
        /// <summary>
        /// Controle ShowData.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ShowData;
        
        /// <summary>
        /// Controle UserData.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do Designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView UserData;
    }
}
